### ISSUE TITLE
Nx version v18.0.7 or higher in technical requirement not sync with package.json

### ISSUE THREAD

**Issue by hannah23280** [PacktPublishing/Effective-Angular#34]
hi, not sure if I see wrongly 
In the technical requirements, it specify v18.0.7, for nx but yet in package.json o
of chapter 2, it is v16.xx for nx package. These not in sync?

**Comment by bsingha27** [comment]
Hi @hannah23280, we recommend using the main branch for the most up-to-date and accurate code. The main branch includes all the code for the book and uses the latest versions of the packages that the author used. Some of the older branches are from before these updates and might not be in sync with the latest versions.
Regardless, the code should still work as expected, and you should be able to follow the steps in these chapters using the feature branches if needed. However, the main branch is the best option for ensuring everything aligns.

We are closing this issue for now. If you encounter any further issues with the code, please feel free to open a new one.
Thanks.
